# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

plugins:
  - jekyll-admin


# Información básica del sitio
title: DevJourneyHub
subtitle: >
  "Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live." - Martin Golding
email: leobip27@gmail.com
intro_es: |
  Tu puerta de entrada digital a mi trayectoria personal y profesional en el mundo de la tecnología. 
  Explora mi portafolio de proyectos de software, descubre publicaciones interesantes sobre tendencias tecnológicas y conoce la historia detrás del código.
  Este es el lugar donde la pasión se encuentra con el propósito, un proyecto a la vez.

intro_en: |
  Your digital gateway to my personal and professional career in the world of technology. 
  Explore my portfolio of software projects, discover interesting posts on technology trends, and learn the history behind the code.
  This is the place where passion meets purpose, one project at a time.
baseurl: "" # Subpath del sitio, e.g. /blog
url: "" # Base URL del sitio, e.g. http://example.com
twitter_username: jekyllrb
github_username: leobip27

# Información del autor
author:
  name: "Leoncio López"
  sub_title: DevOps Automation Engineer
  description_es: |
    Ingeniero DevOps con amplia experiencia en automatización, gestión de bases de datos y optimización de procesos. Especializado en programación Python y desarrollo de arquitecturas de software eficientes y escalables. Apasionado por integrar desarrollo y operaciones, utilizando herramientas como Docker, Kubernetes y Jenkins para optimizar flujos de trabajo mediante la automatización.
  description_en: |
    DevOps Engineer with extensive experience in automation, database management, and process optimization. Specialized in Python programming and developing efficient, scalable software architectures. Passionate about integrating development and operations, using tools like Docker, Kubernetes, and Jenkins to improve workflows through automation.
  about_es: |
    Desde que descubrí mi pasión por la tecnología, he explorado distintas áreas que me han llevado a especializarme en DevOps.
    Empecé mi carrera en bases de datos y programación en VBA y C#, donde aprendí el poder del análisis de datos y la automatización para optimizar procesos.
    Hoy, combino esa experiencia con el desarrollo de arquitecturas de software robustas y escalables, asegurando que los sistemas sean fiables y eficientes.
  about_en: |
    Since discovering my passion for technology, I've explored various fields that led me to specialize in DevOps. I started with databases and VBA/C# programming, learning the power of data analysis and automation to optimize processes. Today, I combine that experience with developing robust, scalable software architectures, ensuring systems are reliable and efficient.
  email: "leobip27@gmail.com"
  linkedin: "https://www.linkedin.com/in/leoncio-lópez-00527474"
  github: "https://github.com/leobip"
  twitter: "https://twitter.com/tu-usuario"
  location: "Madrid, España"

# Ajustes de construcción
theme: minima
markdown: kramdown

# Inclusión de carpetas adicionales
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Configuración de URLs
permalink: pretty

# Exclusión de archivos de la compilación
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor

# Información personal
personal_info:
  name: "Leoncio López"
  title: "DevOps Automation Engineer"
  certifications:
    - title: "Jira Admin. Part 1 & 2"
      year: 2019
    - title: "SonarQube, Install & Analysis"
      year: 2020
    - title: "Polyspace for C/C++ Code Verification"
      institution: "MathWorks"
      year: 2020
    - title: "Google IT Automation with Python (Specialization)"
      institution: "Coursera - Google"
      year: 2021
    - title: "DevOps Culture and Mindset"
      institution: "Coursera - Univ. of California"
      year: 2021
    - title: "Advanced Docker Principles: Docker for Microservices Strategies"
      institution: "Skillsoft"
      Year: 2023
    - title: "Advanced Docker: Exploring Advanced Docker Principles & Practices"
      institution: "Skillsoft"
      Year: 2023
    - title: "AWS Partner: Accreditation (Technical)"
      institution: "AWS Training & Certification"
      Year: 2023
    - title: "Well-Architected Proficient"
      institution: "AWS Training & Certification"
      Year: 2023
    - title: "PRINCE2® Foundation training + exam (7th Edition)"
      institution: "Training360 Kft"
      Year: 2024
    - title: "Advanced PYTHON with CLOUD Computing"
      institution: "Training360 Kft"
      Year: 2024
  experience:
    - job_title: "DevOps Automation Engineer"
      company: "T-Systems Itc Iberia S.A.U."
      period: "03/2023 – Present"
      responsibilities:
        - "Design, develop, and deploy Python scripts and RESTful API functions to automate workflows."
        - "Deploy and manage services using Docker, Kubernetes, and Helm to ensure scalability and reliability."
        - "Create automation scripts for HashiCorp Vault to streamline secrets management."
        - "Administer Linux systems and manage artifacts with JFrog Artifactory and GitLab version control."

    - job_title: "IT Delivery & Automation Engineer"
      company: "HotelBeds Technology, S.L.U."
      period: "07/2022 – 02/2023"
      responsibilities:
        - "Implement GitOps practices and manage deployments with ArgoCD."
        - "Develop CI/CD pipelines in Jenkins/CloudBees using YAML and Groovy for automated software delivery."
        - "Automate infrastructure with Docker, Ansible, Kubernetes, Terraform, and AWS services."
        - "Monitor and optimize performance using Prometheus and Bitbucket."

    - job_title: "DevOps Consultant"
      company: "Vermont Solutions"
      period: "12/2021 – 06/2022"
      responsibilities:
        - "Administer and deploy applications in OpenShift environments."
        - "Develop and maintain Jenkins/CloudBees pipelines using YAML and Groovy for continuous integration."
        - "Write automation scripts in Python, Shell, and Bash to enhance operational efficiency."
        - "Utilize Docker, Ansible, and Kubernetes for container orchestration and deployment."
        - "Conduct static code analysis using SonarQube to ensure code quality."

    - job_title: "GitLab CI/CD Admin & Developer"
      company: "Capitole Consulting, S.L."
      period: "08/2021 – 12/2021"
      responsibilities:
        - "Design and implement CI/CD pipelines and GitLab Runners using YAML and Groovy."
        - "Develop Python and Shell scripts to automate deployment tasks."
        - "Monitor GitLab statistics and system health using Grafana."
        - "Manage remote connections and automate tasks with SSH scripts."

    - job_title: "Technologies and Support Engineer"
      company: "GMV, Innovating Solutions"
      period: "03/2019 – 07/2021"
      responsibilities:
        - "Provide specialized user support and develop applications in Python, Ruby, and VBA."
        - "Perform static code analysis using tools like SonarQube, MathWorks Polyspace, and Sci-Tools Understand."
        - "Develop Python scripts to interact with SonarQube's REST API for data extraction and reporting."
        - "Automate CI/CD processes with Jenkins, Docker, and Git/SVN."
        - "Develop SQL queries and ETL processes using Talend Open Studio."
        - "Configure and run code analysis in MathWorks Polyspace for C/C++ projects."

    - job_title: "Systems Manager"
      company: "Alfa Sistemas, C.A."
      period: "2003 – 2018"
      responsibilities:
        - "Develop and support database applications (Access, VBA, C#) for time management and project control for up to 10,000 users."
        - "Design, install, and configure computer networks, including CISCO routers and switches."
        - "Develop custom Python and VBA applications to meet client-specific needs."
        - "Administer SQL Server databases, including stored procedures, query design, and automation tasks."
        - "Provide remote network support using tools like TeamViewer, Virtual PC, Hyper-V, and VMware."
  skills:
    hard_skills:
      - name: "Python Programming"
        level: "90%"
      - name: "Version Control (Git, SVN, Bitbucket, GitLab)"
        level: "85%"
      - name: "Docker & Containerization"
        level: "90%"
      - name: "Kubernetes, OpenShift, ArgoCD"
        level: "85%"
      - name: "CI/CD Pipelines (Jenkins/CloudBees)"
        level: "90%"
      - name: "Cloud Platforms (AWS)"
        level: "80%"
      - name: "Automation Tools (Ansible, Terraform)"
        level: "85%"
      - name: "Code Quality (SonarQube, Polyspace, Static Analysis, Code Matrics)"
        level: "90%"
      - name: "Shell Scripting (Bash, Linux)"
        level: "85%"

    soft_skills:
      - name: "Effective Communication"
        level: "90%"
      - name: "Problem Solving"
        level: "90%"
      - name: "Team Collaboration"
        level: "90%"
      - name: "Leadership"
        level: "90%"
      - name: "Time Management"
        level: "95%"
      - name: "Adaptability"
        level: "100%"
      - name: "Critical Thinking"
        level: "85%"
