# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

plugins:
  - jekyll-admin


# Información básica del sitio
title: DevJourneyHub
subtitle: >
  "Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live." - Martin Golding
email: leobip27@gmail.com
description: |
  Tu puerta de entrada digital a mi trayectoria personal y profesional en el mundo de la tecnología. 
  Explora mi portafolio de proyectos de software, descubre publicaciones interesantes sobre tendencias tecnológicas y conoce la historia detrás del código.
  Este es el lugar donde la pasión se encuentra con el propósito, un proyecto a la vez.


  Your digital gateway to my personal and professional career in the world of technology. 
  Explore my portfolio of software projects, discover interesting posts on technology trends, and learn the history behind the code.
  This is the place where passion meets purpose, one project at a time.
baseurl: "" # Subpath del sitio, e.g. /blog
url: "" # Base URL del sitio, e.g. http://example.com
twitter_username: jekyllrb
github_username: leobip27

# Información del autor
author:
  name: "Leoncio López"
  sub_title: DevOps Engineer
  description: |
    Soy un ingeniero DevOps apasionado por la tecnología y la programación, con experiencia en bases de datos, automatización, y optimización de procesos. Mi carrera me ha permitido trabajar en múltiples proyectos que combinan desarrollo y operaciones, optimizando tanto sistemas como flujos de trabajo.
  about_es: |
    Siempre he sido un apasionado de la tecnología, con un interés especial en la computación.
    Profesionalmente, comencé mi carrera en bases de datos, atraído por su simplicidad y el poder de extraer y analizar información para mejorar procesos.
    Eventualmente, mi camino me llevó al mundo del DevOps, donde he podido combinar el desarrollo y las operaciones para crear sistemas más eficientes y fiables.
  about_en: |
    I've always been passionate about technology, with a special interest in computing. Professionally, I started in databases, drawn by their simplicity and the power to extract and analyze information to improve processes. Eventually, my journey led me to the world of DevOps, where I've been able to combine development and operations to create more efficient and reliable systems.
  email: "leobip27@gmail.com"
  linkedin: "www.linkedin.com/in/leoncio-lópez-00527474"
  github: "https://github.com/leobip"
  twitter: "https://twitter.com/tu-usuario"
  location: "Madrid, España"

# Ajustes de construcción
theme: minima
markdown: kramdown

# Inclusión de carpetas adicionales
collections:
  projects:
    output: true

# Configuración de URLs
permalink: pretty

# Exclusión de archivos de la compilación
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor

# Información personal
personal_info:
  name: "Leoncio López"
  title: "DevOps Automation Engineer"
  education:
    - title: "Engineer (8th Sem.)"
      institution: "University of Los Andes, Merida, Venezuela"
      year: 1996
  certifications:
    - title: "Jira Admin. Part 1 & 2"
      year: 2019
    - title: "SonarQube, Install & Analysis"
      year: 2020
    - title: "Polyspace for C/C++ Code Verification"
      institution: "MathWorks"
      year: 2020
    - title: "Google IT Automation with Python (Specialization)"
      institution: "Coursera - Google"
      year: 2021
    - title: "DevOps Culture and Mindset"
      institution: "Coursera - Univ. of California"
      year: 2021
  experience:
    - job_title: "DevOps Automation Engineer"
      company: "T-Systems Itc Iberia S.A.U."
      period: "03/2023 – present"
      responsibilities:
        - "Design, develop, and deploy Python scripts, API-REST Functions"
        - "Deployment services using Docker, Kubernetes, Helm"
        - "Install & Develop automation scripts for Hashicorp Vault"
        - "Linux, Jfrog Artifactory, GitLab Version Control"
    - job_title: "IT Delivery & Automation Engineer"
      company: "HotelBeds Technology, S.L.U."
      period: "06/2022 – 02/2023"
      responsibilities:
        - "Git-Ops, ArgoCD Administration & Deployments"
        - "Design, develop, and implement Jenkins/CloudBees Pipelines using Yaml, Groovy"
        - "Docker, Ansible, Kubernetes, Terraform, AWS, Bitbucket, Prometheus"
  skills:
    hard_skills:
      - name: "Python"
        level: "90%"
      - name: "C#"
        level: "70%"
      - name: "Docker"
        level: "85%"
      - name: "Kubernetes"
        level: "85%"
      - name: "Jenkins"
        level: "90%"
      - name: "SonarQube"
        level: "90%"
    soft_skills:
      - name: "Communication"
        level: "85"
      - name: "Leadership"
        level: "75"
