# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Leo DevJourneyHub
subtitle: >
  Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live. - Martin Golding
email: leobip27@gmail.com
description: |
  Tu puerta de entrada digital a mi trayectoria personal y profesional en el mundo de la tecnología. 
  Explora mi portafolio de proyectos de software, descubre publicaciones interesantes que me llaman la atención sobre las últimas tendencias tecnológicas y conoce la historia detrás del código. Aquí es donde la pasión se encuentra con el propósito, un proyecto a la vez.

  Your digital gateway to my personal and professional journey in the world of technology. 
  Explore my portfolio of software projects, discover interesting posts that catch my attention on the latest tech trends, and learn the story behind the code. This is where passion meets purpose, one project at a time.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  leobip27

author:
  name: "Leoncio Lopez Pelayo"
  sub_title: DevOps Engineer
  description:
  about_es: |
    Siempre he sido un apasionado de la tecnología, con un interés especial en la computación.
    Mis aficiones van desde los cómics, el cine y la música (disfruto de todo, desde rock hasta jazz y blues) hasta viajar,
    explorar nuevas culturas y sumergirme en la historia.

    Profesionalmente, comencé mi carrera en el área de bases de datos, atraído por su simplicidad y el poder de extraer y analizar información para mejorar procesos.
    Esta pasión me llevó a profundizar en la programación, donde descubrí nuevas formas de optimizar y automatizar tareas. 
    Eventualmente, mi camino me llevó al mundo del DevOps, donde he podido combinar el desarrollo y las operaciones para crear sistemas más eficientes y fiables.

    En DevOps, he trabajado en la creación de pipelines de CI/CD, implementado infraestructuras como código (IaC) y mejorado la monitorización y rendimiento de aplicaciones.
    Python, en particular, se ha convertido en mi herramienta favorita por su versatilidad, permitiéndome automatizar tareas y simplificar procesos complejos.
  about_en: |
    I've always been passionate about technology, with a special interest in computing. My hobbies range from comics, movies, and music (I enjoy everything from rock to jazz and blues) to traveling, exploring new cultures, and immersing myself in history.

    Professionally, I began my career in the field of databases, drawn by their simplicity and the power to extract and analyze information to improve processes. This passion led me to dive deeper into programming, where I discovered new ways to optimize and automate tasks. Eventually, my journey led me to the world of DevOps, where I've been able to combine development and operations to create more efficient and reliable systems.

    In DevOps, I've worked on creating CI/CD pipelines, implementing infrastructure as code (IaC), and improving application monitoring and performance. Python, in particular, has become my favorite tool for its versatility, allowing me to automate tasks and simplify complex processes.
  email: "leobip27@gmail.com"
  linkedin: "www.linkedin.com/in/leoncio-lópez-00527474"
  github: "https://github.com/leobip"
  twitter: "https://twitter.com/tu-usuario"
  location: "Madrid, España"
  #photo: "/images/your-photo.jpg"



# Build settings
theme: minima
markdown: kramdown


# Incluir carpetas adicionales
collections:
  projects:
    output: true

# Build settings
permalink: pretty


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
